-- FinTrust report-first V1 reference schema, PostgreSQL 16+.
-- UUIDs are generated by the application; all JSON payloads are Zod validated.
BEGIN;

CREATE TABLE IF NOT EXISTS workspaces (
  id uuid PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY,
  oidc_issuer text NOT NULL,
  oidc_subject text NOT NULL,
  display_name text NOT NULL,
  UNIQUE (oidc_issuer, oidc_subject)
);

CREATE TABLE IF NOT EXISTS memberships (
  workspace_id uuid NOT NULL REFERENCES workspaces(id),
  user_id uuid NOT NULL REFERENCES users(id),
  role text NOT NULL DEFAULT 'OWNER' CHECK (role = 'OWNER'),
  PRIMARY KEY (workspace_id, user_id)
);

CREATE TABLE IF NOT EXISTS sessions (
  token_hash text PRIMARY KEY,
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  csrf_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  FOREIGN KEY (workspace_id, user_id) REFERENCES memberships(workspace_id, user_id)
);

CREATE TABLE IF NOT EXISTS companies (
  id uuid PRIMARY KEY,
  name text NOT NULL,
  exchange text NOT NULL CHECK (exchange IN ('SSE','SZSE')),
  security_code text NOT NULL,
  issuer_ids jsonb NOT NULL DEFAULT '{}',
  aliases jsonb NOT NULL DEFAULT '[]',
  UNIQUE(exchange, security_code)
);

CREATE TABLE IF NOT EXISTS projects (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id),
  company_id uuid REFERENCES companies(id),
  title text NOT NULL,
  current_version integer NOT NULL DEFAULT 0 CHECK (current_version >= 0),
  archived boolean NOT NULL DEFAULT false,
  monitor_enabled boolean NOT NULL DEFAULT false,
  last_checked_at timestamptz,
  next_check_at timestamptz,
  pending_source_change boolean NOT NULL DEFAULT false,
  method jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS documents (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id),
  company_id uuid REFERENCES companies(id),
  role text NOT NULL CHECK (role IN ('THESIS_SOURCE','FINANCIAL_FILING','SUPPLEMENT')),
  origin text NOT NULL CHECK (origin IN ('USER_UPLOAD','OFFICIAL_DISCLOSURE','LEGACY_TEXT')),
  title text NOT NULL,
  file_name text NOT NULL,
  mime_type text NOT NULL,
  bytes bigint NOT NULL CHECK(bytes >= 0),
  sha256 text NOT NULL CHECK(length(sha256)=64),
  storage_key text NOT NULL,
  published_at timestamptz,
  period jsonb,
  official_url text,
  provider_id text,
  supersedes_document_id uuid,
  is_synthetic boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(workspace_id, id),
  FOREIGN KEY(workspace_id, supersedes_document_id) REFERENCES documents(workspace_id, id)
);

CREATE INDEX IF NOT EXISTS documents_sha ON documents(workspace_id, sha256);

CREATE TABLE IF NOT EXISTS document_parses (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  parser_version text NOT NULL,
  options_hash text NOT NULL,
  artifact_key text NOT NULL,
  page_count integer NOT NULL CHECK(page_count >= 0),
  quality jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(workspace_id, id),
  UNIQUE(document_id, parser_version, options_hash),
  FOREIGN KEY(workspace_id, document_id) REFERENCES documents(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS evidence_spans (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  parse_id uuid NOT NULL,
  page_number integer CHECK(page_number >= 1),
  regions jsonb NOT NULL,
  quote text NOT NULL,
  text_hash text NOT NULL,
  quality text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}',
  UNIQUE(workspace_id, id),
  FOREIGN KEY(workspace_id, parse_id) REFERENCES document_parses(workspace_id, id)
);

CREATE INDEX IF NOT EXISTS evidence_by_page ON evidence_spans(parse_id, page_number);

CREATE TABLE IF NOT EXISTS facts (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  document_id uuid NOT NULL,
  company_id uuid NOT NULL REFERENCES companies(id),
  metric text NOT NULL,
  segment text,
  period_start date,
  period_end date NOT NULL,
  basis text NOT NULL CHECK(basis IN ('YEAR','YTD','QUARTER','INSTANT')),
  scope text NOT NULL CHECK(scope IN ('CONSOLIDATED','PARENT','SEGMENT')),
  nature text NOT NULL CHECK(nature IN ('ACTUAL','FORECAST','GUIDANCE')),
  value numeric NOT NULL,
  unit text NOT NULL,
  currency text,
  restatement_key text NOT NULL,
  extraction_version text NOT NULL,
  identity_hash text NOT NULL,
  payload jsonb NOT NULL,
  UNIQUE(workspace_id, id),
  UNIQUE(document_id, identity_hash, extraction_version),
  CHECK((basis='INSTANT' AND period_start IS NULL) OR (basis<>'INSTANT' AND period_start IS NOT NULL)),
  FOREIGN KEY(workspace_id, document_id) REFERENCES documents(workspace_id, id)
);

CREATE INDEX IF NOT EXISTS facts_lookup ON facts(workspace_id, company_id, metric, period_end, basis, scope);

CREATE TABLE IF NOT EXISTS fact_evidence (
  workspace_id uuid NOT NULL,
  fact_id uuid NOT NULL,
  evidence_id uuid NOT NULL,
  PRIMARY KEY(fact_id, evidence_id),
  FOREIGN KEY(workspace_id, fact_id) REFERENCES facts(workspace_id, id),
  FOREIGN KEY(workspace_id, evidence_id) REFERENCES evidence_spans(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS calculations (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id),
  formula_id text NOT NULL,
  formula_version text NOT NULL,
  input_hash text NOT NULL,
  result numeric,
  payload jsonb NOT NULL,
  UNIQUE(workspace_id, id),
  UNIQUE(workspace_id, formula_id, formula_version, input_hash)
);

CREATE TABLE IF NOT EXISTS theses (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  lifecycle text NOT NULL CHECK(lifecycle IN ('ACTIVE','ARCHIVED')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(workspace_id, id),
  UNIQUE(workspace_id, project_id, id),
  FOREIGN KEY(workspace_id, project_id) REFERENCES projects(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS thesis_revisions (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  thesis_id uuid NOT NULL,
  revision integer NOT NULL CHECK(revision >= 1),
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(workspace_id, id),
  UNIQUE(thesis_id, revision),
  FOREIGN KEY(workspace_id, thesis_id) REFERENCES theses(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS runs (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  kind text NOT NULL CHECK(kind IN ('INITIAL_REPORT','ADD_REPORT','REFRESH_FILINGS','REVIEW_STATE')),
  status text NOT NULL CHECK(status IN ('QUEUED','RUNNING','WAITING_USER','AWAITING_REVIEW','COMPLETED','FAILED','CANCELLED','SUPERSEDED')),
  phase text,
  base_state_version integer NOT NULL,
  as_of timestamptz NOT NULL,
  required_input jsonb,
  source_manifest jsonb,
  budget jsonb NOT NULL,
  error jsonb,
  completion_reason text,
  cancel_requested boolean NOT NULL DEFAULT false,
  config_manifest jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(workspace_id, id),
  UNIQUE(workspace_id, project_id, id),
  FOREIGN KEY(workspace_id, project_id) REFERENCES projects(workspace_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS one_active_run ON runs(project_id)
  WHERE status IN ('QUEUED','RUNNING','WAITING_USER','AWAITING_REVIEW');
CREATE INDEX IF NOT EXISTS runs_by_project ON runs(project_id, created_at DESC, id);

CREATE TABLE IF NOT EXISTS run_documents (
  workspace_id uuid NOT NULL,
  run_id uuid NOT NULL,
  document_id uuid NOT NULL,
  purpose text NOT NULL,
  PRIMARY KEY(run_id, document_id),
  FOREIGN KEY(workspace_id, run_id) REFERENCES runs(workspace_id, id),
  FOREIGN KEY(workspace_id, document_id) REFERENCES documents(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS run_checkpoints (
  workspace_id uuid NOT NULL,
  run_id uuid NOT NULL,
  phase text NOT NULL,
  input_hash text NOT NULL,
  schema_version text NOT NULL,
  payload jsonb NOT NULL,
  committed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(run_id, phase, input_hash),
  FOREIGN KEY(workspace_id, run_id) REFERENCES runs(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS jobs (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id),
  run_id uuid,
  kind text NOT NULL CHECK(kind IN ('RUN','CHECK_DISCLOSURES','EXPORT')),
  dedupe_key text NOT NULL,
  payload jsonb NOT NULL,
  status text NOT NULL CHECK(status IN ('QUEUED','RUNNING','DONE','FAILED','CANCELLED')),
  priority integer NOT NULL DEFAULT 0,
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 3,
  available_at timestamptz NOT NULL DEFAULT now(),
  lease_owner text,
  lease_token uuid,
  lease_until timestamptz,
  last_error jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(workspace_id, dedupe_key),
  FOREIGN KEY(workspace_id, run_id) REFERENCES runs(workspace_id, id)
);

CREATE INDEX IF NOT EXISTS jobs_ready ON jobs(status, available_at, priority DESC);
CREATE INDEX IF NOT EXISTS jobs_expired ON jobs(lease_until) WHERE status='RUNNING';

CREATE TABLE IF NOT EXISTS run_events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  workspace_id uuid NOT NULL,
  run_id uuid NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(workspace_id, run_id) REFERENCES runs(workspace_id, id)
);

CREATE INDEX IF NOT EXISTS events_stream ON run_events(run_id, id);

CREATE TABLE IF NOT EXISTS drafts (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  run_id uuid NOT NULL,
  revision integer NOT NULL DEFAULT 1,
  input_hash text NOT NULL,
  payload jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(workspace_id, id),
  UNIQUE(run_id),
  FOREIGN KEY(workspace_id, run_id) REFERENCES runs(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS research_updates (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  run_id uuid NOT NULL,
  version integer NOT NULL CHECK(version >= 1),
  base_version integer NOT NULL,
  confirmed_by uuid NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(workspace_id, id),
  UNIQUE(project_id, version),
  UNIQUE(run_id),
  FOREIGN KEY(workspace_id, project_id, run_id) REFERENCES runs(workspace_id, project_id, id),
  FOREIGN KEY(workspace_id, confirmed_by) REFERENCES memberships(workspace_id, user_id)
);

CREATE TABLE IF NOT EXISTS research_states (
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  version integer NOT NULL,
  update_id uuid NOT NULL,
  payload jsonb NOT NULL,
  state_hash text NOT NULL,
  PRIMARY KEY(project_id, version),
  FOREIGN KEY(workspace_id, project_id) REFERENCES projects(workspace_id, id),
  FOREIGN KEY(workspace_id, update_id) REFERENCES research_updates(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS user_corrections (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  thesis_id uuid,
  update_id uuid NOT NULL,
  kind text NOT NULL,
  action text NOT NULL CHECK(action IN ('SET','CLEAR')),
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(workspace_id, project_id) REFERENCES projects(workspace_id, id),
  FOREIGN KEY(workspace_id, project_id, thesis_id) REFERENCES theses(workspace_id, project_id, id),
  FOREIGN KEY(workspace_id, update_id) REFERENCES research_updates(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS research_questions (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  thesis_id uuid NOT NULL,
  status text NOT NULL CHECK(status IN ('OPEN','ANSWERED','DEFERRED')),
  payload jsonb NOT NULL,
  last_update_id uuid NOT NULL,
  FOREIGN KEY(workspace_id, project_id, thesis_id) REFERENCES theses(workspace_id, project_id, id),
  FOREIGN KEY(workspace_id, last_update_id) REFERENCES research_updates(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS source_checks (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  provider text NOT NULL,
  checked_at timestamptz NOT NULL,
  status text NOT NULL,
  payload jsonb NOT NULL,
  FOREIGN KEY(workspace_id, project_id) REFERENCES projects(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS model_calls (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  run_id uuid NOT NULL,
  stage text NOT NULL,
  provider text NOT NULL,
  model text NOT NULL,
  prompt_version text NOT NULL,
  request_hash text NOT NULL,
  status text NOT NULL,
  input_tokens integer,
  output_tokens integer,
  estimated_cost numeric,
  currency text,
  latency_ms integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}',
  FOREIGN KEY(workspace_id, run_id) REFERENCES runs(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS idempotency_keys (
  workspace_id uuid NOT NULL REFERENCES workspaces(id),
  operation text NOT NULL,
  key text NOT NULL,
  request_hash text NOT NULL,
  response_status integer,
  response_payload jsonb,
  expires_at timestamptz NOT NULL,
  PRIMARY KEY(workspace_id, operation, key)
);

CREATE TABLE IF NOT EXISTS exports (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  project_id uuid NOT NULL,
  state_version integer NOT NULL,
  include_files boolean NOT NULL,
  status text NOT NULL CHECK(status IN ('QUEUED','RUNNING','COMPLETED','FAILED')),
  storage_key text,
  error jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(workspace_id, project_id) REFERENCES projects(workspace_id, id)
);

CREATE INDEX IF NOT EXISTS project_list ON projects(workspace_id, updated_at DESC, id);
CREATE INDEX IF NOT EXISTS project_monitor ON projects(next_check_at) WHERE monitor_enabled=true AND archived=false;

COMMIT;
